name: Build and Package Extension

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Install Haxelibs
        run: |
          haxelib install hxnodejs 12.2.0
          haxelib install vscode 1.60.0

      - name: Compile HXML
        run: haxe build.hxml

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Package extension
        run: |
          cd out
          vsce package

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: out/*.vsix